-- test datasets for memory db mode
INSERT INTO GAME_RESULTS (ID, WINNER, USERNAME, PLAYER_CHOICE, COMPUTER_CHOICE) VALUES (1, 'c', 'foo', 'r', 'p') ;
INSERT INTO GAME_RESULTS (ID, WINNER, USERNAME, PLAYER_CHOICE, COMPUTER_CHOICE) VALUES (2, 'p', 'foo', 'r', 's') ;
INSERT INTO GAME_RESULTS (ID, WINNER, USERNAME, PLAYER_CHOICE, COMPUTER_CHOICE) VALUES (3, 'd', 'foo', 's', 's') ;
INSERT INTO GAME_RESULTS (ID, WINNER, USERNAME, PLAYER_CHOICE, COMPUTER_CHOICE) VALUES (4, 'c', 'bar', 's', 'r') ;
